### ISSUE TITLE
Github Pages

### ISSUE THREAD

**Issue by kovacspatrik** [Teaching-projects/SZE-MOSZE-2021-R4kt-rV4ad-sz0k#1]
@hegyhati Van rá mód, hogy a GitHub Pages-ben módosítani tudjam az elérési utat admin jogosultság nélkül? :)

**Comment by hegyhati** [comment]
Marmint azt szeretned modositani, hogy melyik konyvtarat hostolja? Szerintem admin jogosultsag nelkul azt nem lehet. Ha megirod, mire allitsam, beallitom. De mit akartok kirakni github pages-re? Generalt cuccot fo branch-be fel ne commitoljatok. Tehat ha pl fejlesztoi dokumentacio, akkor annak legyen egy teljesen separate branch, ott meg akkor lehet a gyokertben.

**Comment by kovacspatrik** [comment]
A doxygen dokumentációról lenne szó, a gh-pages branchen található.

**Comment by hegyhati** [comment]
Elmeletileg beallitottam `gh-pages/root`-ra. Ha lesz uj commit, itt fog megjelenni: https://teaching-projects.github.io/SZE-MOSZE-2021-R4kt-rV4ad-sz0k/

Ha mukodik, close-oljatok az issue-t, ha nem, akkor szoljatok.

**Comment by hegyhati** [comment]
och, meg uj comit sem kellett, lebuildelte. akkor done.
