### ISSUE TITLE
Repo ellenőrzés

### ISSUE THREAD

**Issue by kovacspatrik** [Teaching-projects/SZE-MOSZE-2021-R4kt-rV4ad-sz0k#2]
@hegyhati légyszíves nézz rá a repora, hogy hiányzik-e még belőle valami?

**Comment by hegyhati** [comment]
Rendben levonek tunik a dolog, a ket bemutato videot nem latom.

**Comment by kovacspatrik** [comment]
Igen, azokkal még adósok vagyunk, készítjük! Köszönjük!

**Comment by kovacspatrik** [comment]
@hegyhati elkészültek a videók, ha minden igaz akkor a repo így véglegesnek tekinthető! :)

**Comment by hegyhati** [comment]
No bocsi, most tudtam ranezni. A relativ javasolt erdemjegynek mindenkihez 3-ast irtatok, ezt ugy ertitek, hogy 3-asnak ertekelitek a munkat? En bevallom a 4-eshez huzok inkabb :-) NEm lett csillivilli, a funkcionalitas nem utos, de a fontosabb MOSZE-s dolgok bennevannak, meg ha kilora nem is sok. Szoval legyen 4, remelem hasznos volt foglalkozni vele, aztan majd hajra a tobbihez is, mar amelyikotoknek meg van. Neptunt mindjart ugyezem.
